### ISSUE TITLE
iPhone/iPod touch の一部のサイズでヘッダーがはみ出る

### ISSUE THREAD

**Issue by rinsuki** [lonsagisawa/aquaskk-web#3]
例: iPod touch 7th gen (320px)

<img height="504" alt="image" src="https://user-images.githubusercontent.com/6533808/100544263-d03c5f00-3297-11eb-99d6-9349c053523c.png">

`<meta name="viewport">` を消すなり `initial-scale` 変えるなり文字を小さくするなりしたほうがよさそう

**Comment by lonsagisawa** [comment]
モバイルのことすっかり忘れていたナリ メディアクエリでなんとかします

**Comment by lonsagisawa** [comment]
<img width="796" alt="スクリーンショット 2020-11-29 23 19 57" src="https://user-images.githubusercontent.com/5173607/100544516-92403a80-3299-11eb-9425-6775bb8b59ad.png">
なおしました
